default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit new beta build for testing"
  lane :beta do
     sh "flutter build apk -v --build-number #{ENV['GITVERSION_BUILDMETADATA']} --build-name #{ENV['GITVERSION_MAJORMINORPATCH']}"
        firebase_app_distribution(
          app: "1:598133513450:android:9712712105eab7478e0b93",
          testers: "hirathameem@ymail.com",
          release_notes: "Lots of amazing new features to test out!" ,
          firebase_cli_token: ENV['FIREBASE_TOKEN_STARTUP1'],
          android_artifact_type: "APK",
          android_artifact_path: '../build/app/outputs/flutter-apk/app-release.apk'
        )
     end

  
  desc "Promote Internal to Alpha"
  lane :promote_internal_to_alpha do
      upload_to_play_store(
        package_name: 'com.nathira.startup1', 
        track: 'internal', 
        track_promote_to: 'alpha'
        #aab: '../build/app/outputs/bundle/release/app-release.aab',
        #json_key: "service_account_key.json"
        )
  end
end