default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit new beta build for testing"
  lane :beta do
     sh "flutter build apk"
        firebase_app_distribution(
          app: "1:598133513450:android:f5f228d19586ee208e0b93",
          testers: "hirathameem@ymail.com",
          release_notes: "Lots of amazing new features to test out!",
          firebase_cli_token: ENV['FIREBASE_TOKEN'],
          android_artifact_type: "APK",
          android_artifact_path: '../build/app/outputs/flutter-apk/app-release.apk'
        )
     end



    desc "Deploy a beta version to the Google Play"
    lane :playstore do
      gradle(task: 'clean assembleRelease')
      upload_to_play_store(

        version_name: "1.0.1",
        version_code: 3,
        )
      end
   end
