# cd.yml
name: CD

on:
  push:
    branches:
      - "v1.5.8"

jobs:
  generate_release:
    outputs:
      changelog: ${{ steps.build_release.outputs.changelog }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Changelog
        id: build_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: ".github/configs/configuration.json"
          repo: "startup1"
          fromTag: "v1.1.0"
          toTag: "main"
          includeOpen: false
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}

  # CI
  build_android:
    runs-on: ubuntu-latest
    needs: generate_release
#    defaults:
#      run:
#        working-directory: .android
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_secrets.sh
        env:
          ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: "3.3.1"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "3.1.420"
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: "5.10.0"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.13
      - name: Build the bundle
        run: flutter build appbundle --release
      - name: Upload artifact to Github
        uses: actions/upload-artifact@v1
        with:
          name: release-aab
          path: build/app/outputs//bundle/release/app-release.aab




  # CD
  deploy_android:
    runs-on: ubuntu-latest
    needs: [build_android]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_secrets.sh
        env:
          ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: "3.3.1"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "3.1.420"
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: "5.10.0"
      # - name: Determine Version
      #   id: gitversion
      #   uses: gittools/actions/gitversion/execute@v0.9.13
      - name: Build the bundle
        run: flutter build appbundle --release
      - name: Run Fastlane
        #run: bundle exec fastlane deploy
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: promote_internal
          subdirectory: android
        
      